import type {
  Lead,
  Property,
  Client,
  FollowUp,
  Task,
  SiteVisit,
  Deal,
  Activity,
} from '../types';

export const DEMO_AGENTS = [
  { id: 'agent-1', name: 'Rahul Mehta', role: 'agent' as const, email: 'rahul.mehta@primespace.in' },
  { id: 'agent-2', name: 'Neha Sharma', role: 'agent' as const, email: 'neha.sharma@primespace.in' },
  { id: 'agent-3', name: 'Arjun Kapoor', role: 'agent' as const, email: 'arjun.kapoor@primespace.in' },
];

export function generateDemoLeads(agentId: string, agentName: string): Omit<Lead, 'id'>[] {
  const sources = ['MagicBricks', '99acres', 'Housing.com', 'Website', 'Referral', 'Walk-in', 'Meta Ads'];
  const statuses: Lead['status'][] = ['New', 'Contacted', 'Qualified', 'Site Visit', 'Negotiation', 'Won', 'Lost'];
  const priorities: Lead['priority'][] = ['Hot', 'Warm', 'Cold'];

  return [
    {
      name: 'Vikramaditya Singhania',
      phone: '+91 98112 34567',
      whatsapp: '+91 98112 34567',
      email: 'vikram.singhania@gmail.com',
      source: 'MagicBricks',
      budgetMin: 35000000,
      budgetMax: 50000000,
      propertyType: 'Apartment',
      preferredLocation: 'Golf Course Road, Gurugram',
      purpose: 'Buy',
      bedrooms: '4+ BHK',
      status: 'Negotiation',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Looking for luxury high-rise condominium with Aravali view. DLF The Camellias or The Aralias preferred.',
      nextFollowUpDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
      isDemo: true,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      name: 'Ananya Deshmukh',
      phone: '+91 98201 98765',
      whatsapp: '+91 98201 98765',
      email: 'ananya.deshmukh@outlook.com',
      source: 'Website',
      budgetMin: 18000000,
      budgetMax: 24000000,
      propertyType: 'Apartment',
      preferredLocation: 'Golf Course Ext Road, Sector 66',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'Qualified',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'VP at MNC Cyber City. Needs clubhouse amenities, modular kitchen and 2 covered parking spots.',
      nextFollowUpDate: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
      isDemo: true,
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      name: 'Rohan Sethi',
      phone: '+91 99990 12345',
      whatsapp: '+91 99990 12345',
      email: 'rohan.sethi@techcorp.io',
      source: '99acres',
      budgetMin: 12000000,
      budgetMax: 16000000,
      propertyType: 'Apartment',
      preferredLocation: 'Sector 57, Gurugram',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'Site Visit',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Interested in builder floors or gated societies near Rapid Metro Sector 55-56.',
      nextFollowUpDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
      isDemo: true,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      name: 'Dr. Meenakshi Iyer',
      phone: '+91 98711 55443',
      whatsapp: '+91 98711 55443',
      email: 'meenakshi.iyer@medanta.org',
      source: 'Referral',
      budgetMin: 45000000,
      budgetMax: 65000000,
      propertyType: 'Villa',
      preferredLocation: 'DLF Phase 1, Gurugram',
      purpose: 'Buy',
      bedrooms: '4+ BHK',
      status: 'Qualified',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Senior consultant doctor seeking independent villa/kothi with private garden.',
      nextFollowUpDate: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
      isDemo: true,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      name: 'Kavita & Amit Bansal',
      phone: '+91 98100 44321',
      whatsapp: '+91 98100 44321',
      email: 'amit.bansal@bansalexports.com',
      source: 'Housing.com',
      budgetMin: 80000,
      budgetMax: 120000,
      propertyType: 'Apartment',
      preferredLocation: 'DLF Phase 2, Gurugram',
      purpose: 'Rent',
      bedrooms: '3 BHK',
      status: 'Contacted',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Looking for fully furnished luxury rental near CyberHub. Relocating from Bangalore.',
      isDemo: true,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      name: 'Harpreet Singh Gill',
      phone: '+91 98760 33221',
      whatsapp: '+91 98760 33221',
      email: 'hsgill@canadagroup.ca',
      source: 'Website',
      budgetMin: 50000000,
      budgetMax: 90000000,
      propertyType: 'Plot',
      preferredLocation: 'Sohna Road / Southern Peripheral Road',
      purpose: 'Investment',
      bedrooms: 'Plot',
      status: 'Qualified',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'NRI investor based in Vancouver. Evaluating gated plots in Vatika City or DLF Gardencity.',
      isDemo: true,
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
    {
      name: 'Siddharth Oberoi',
      phone: '+91 97118 77665',
      whatsapp: '+91 97118 77665',
      email: 'siddharth@oberoiventures.com',
      source: 'Walk-in',
      budgetMin: 25000000,
      budgetMax: 35000000,
      propertyType: 'Commercial',
      preferredLocation: 'Golf Course Extension Road',
      purpose: 'Investment',
      bedrooms: 'Commercial',
      status: 'Won',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Closed retail shop space at M3M Urbana. Lease guarantee in place.',
      isDemo: true,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      name: 'Pooja Narang',
      phone: '+91 99102 33445',
      email: 'pooja.narang@gmail.com',
      source: 'Meta Ads',
      budgetMin: 8500000,
      budgetMax: 11000000,
      propertyType: 'Apartment',
      preferredLocation: 'Sector 150, Noida Expressway',
      purpose: 'Buy',
      bedrooms: '2 BHK',
      status: 'New',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Looking for green-facing tower in ATS or Godrej properties near Jewar Airport corridor.',
      isDemo: true,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      name: 'Gaurav Aggarwal',
      phone: '+91 98188 99887',
      whatsapp: '+91 98188 99887',
      email: 'gaurav.aggarwal@fintech.co',
      source: 'MagicBricks',
      budgetMin: 15000000,
      budgetMax: 20000000,
      propertyType: 'Apartment',
      preferredLocation: 'Dwarka Expressway, Sector 109',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'Contacted',
      priority: 'Cold',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Initial inquiry taken. Comparing with projects in New Gurugram Sector 82.',
      isDemo: true,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      name: 'Tanya Mathur',
      phone: '+91 98733 11223',
      email: 'tanya.mathur@delhicapitals.in',
      source: 'Referral',
      budgetMin: 22000000,
      budgetMax: 28000000,
      propertyType: 'Apartment',
      preferredLocation: 'Sector 49, Sohna Road',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'Site Visit',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Site visit completed for Vatika City penthouse. Negotiating on token amount.',
      isDemo: true,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      name: 'Sunil & Renu Kapoor',
      phone: '+91 98114 66778',
      email: 'sunil.kapoor@kgroup.org',
      source: 'Website',
      budgetMin: 30000000,
      budgetMax: 40000000,
      propertyType: 'Independent House',
      preferredLocation: 'Sushant Lok 1, Gurugram',
      purpose: 'Buy',
      bedrooms: '4+ BHK',
      status: 'Qualified',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Wants ground + 2 floors independent kothi near Galleria Market.',
      isDemo: true,
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      name: 'Deepak Varma',
      phone: '+91 98210 55432',
      email: 'dvarma@consulting.com',
      source: '99acres',
      budgetMin: 45000,
      budgetMax: 60000,
      propertyType: 'Apartment',
      preferredLocation: 'Sector 56, Golf Course Road',
      purpose: 'Rent',
      bedrooms: '2 BHK',
      status: 'Won',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Finalized rental agreement for 2 BHK furnished flat in Devinder Vihar.',
      isDemo: true,
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
    {
      name: 'Kunal Khanna',
      phone: '+91 99119 88776',
      whatsapp: '+91 99119 88776',
      email: 'kkhanna@khannas.in',
      source: 'Housing.com',
      budgetMin: 65000000,
      budgetMax: 85000000,
      propertyType: 'Villa',
      preferredLocation: 'Tata Primanti, Sector 72',
      purpose: 'Buy',
      bedrooms: '4+ BHK',
      status: 'Negotiation',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Interested in executive villa. Price difference of 35 Lakhs under discussion with seller.',
      isDemo: true,
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      name: 'Simran Jolly',
      phone: '+91 98105 22334',
      email: 'simran.jolly@mediaworks.com',
      source: 'Website',
      budgetMin: 14000000,
      budgetMax: 18000000,
      propertyType: 'Apartment',
      preferredLocation: 'Sector 67, Gurugram',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'New',
      priority: 'Cold',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Requested brochure and floor plans for Ireo Victory Valley and Bestech Park View.',
      isDemo: true,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      name: 'Alok Nath Pandey',
      phone: '+91 98710 44556',
      email: 'alok.pandey@railinfra.in',
      source: 'Walk-in',
      budgetMin: 9500000,
      budgetMax: 12500000,
      propertyType: 'Apartment',
      preferredLocation: 'Faridabad Sector 82',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'Lost',
      priority: 'Cold',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Postponed purchase due to job transfer to Kolkata.',
      isDemo: true,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      name: 'Manish Chawla',
      phone: '+91 98110 99001',
      email: 'manish@chawlatextiles.com',
      source: 'Referral',
      budgetMin: 35000000,
      budgetMax: 55000000,
      propertyType: 'Commercial',
      preferredLocation: 'Udyog Vihar Phase 4, Gurugram',
      purpose: 'Buy',
      bedrooms: 'Commercial',
      status: 'Qualified',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Looking for industrial/commercial building or floor for apparel export office.',
      isDemo: true,
      createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      name: 'Prateek & Richa Roy',
      phone: '+91 99991 88223',
      whatsapp: '+91 99991 88223',
      email: 'prateek.roy@google.com',
      source: 'MagicBricks',
      budgetMin: 28000000,
      budgetMax: 36000000,
      propertyType: 'Apartment',
      preferredLocation: 'Golf Course Extension Road',
      purpose: 'Buy',
      bedrooms: '4+ BHK',
      status: 'Site Visit',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Shortlisted Pioneer Araya and Trump Tower. Re-visit scheduled with parents this Saturday.',
      isDemo: true,
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      name: 'Tarun Bhatia',
      phone: '+91 98180 77112',
      email: 'tarun.bhatia@autolink.in',
      source: 'Meta Ads',
      budgetMin: 70000,
      budgetMax: 90000,
      propertyType: 'Apartment',
      preferredLocation: 'Nirvana Country, Sector 50',
      purpose: 'Rent',
      bedrooms: '3 BHK',
      status: 'Contacted',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Requires pet-friendly ground floor flat with attached lawn.',
      isDemo: true,
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      name: 'Smita Kulkarni',
      phone: '+91 98200 44551',
      email: 'smita.k@analytics.com',
      source: 'Website',
      budgetMin: 16000000,
      budgetMax: 21000000,
      propertyType: 'Apartment',
      preferredLocation: 'Dwarka Sector 19B, Delhi',
      purpose: 'Buy',
      bedrooms: '3 BHK',
      status: 'New',
      priority: 'Warm',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Interested in DDA Golf Course apartments or CGHS societies in Dwarka.',
      isDemo: true,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      name: 'Rajeev & Priya Malik',
      phone: '+91 98101 66554',
      whatsapp: '+91 98101 66554',
      email: 'rajeev.malik@maliklaw.in',
      source: 'Referral',
      budgetMin: 42000000,
      budgetMax: 58000000,
      propertyType: 'Apartment',
      preferredLocation: 'DLF Phase 5, Gurugram',
      purpose: 'Buy',
      bedrooms: '4+ BHK',
      status: 'Qualified',
      priority: 'Hot',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Senior Supreme Court advocate. Looking for luxury flat in DLF Pinnacle or Westend Heights.',
      isDemo: true,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
  ];
}

export function generateDemoProperties(agentId: string, agentName: string): Omit<Property, 'id'>[] {
  return [
    {
      propertyCode: 'PROP-1001',
      title: 'Luxury 4 BHK Sky Villa in DLF The Magnolias',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 185000000,
      location: 'DLF Phase 5, Golf Course Road',
      address: 'Tower B, 14th Floor, DLF The Magnolias',
      city: 'Gurugram',
      locality: 'DLF Phase 5',
      bedrooms: 4,
      bathrooms: 5,
      area: 6350,
      furnishing: 'Semi-Furnished',
      floor: 14,
      totalFloors: 25,
      parking: 3,
      facing: 'North-East',
      possessionStatus: 'Ready to Move',
      description: 'Ultra-exclusive luxury apartment offering unhindered vistas of the DLF Golf Course. Features private elevator foyer, Italian marble flooring throughout, imported poggenpohl modular kitchen, VRV air-conditioning, servant quarters, and expansive balcony wrap.',
      amenities: ['Golf Course View', 'Private Elevator', 'Swimming Pool', 'Spa & Salon', 'Gymnasium', 'Tennis Court', 'Clubhouse', 'Concierge Service', '24x7 High Security'],
      ownerName: 'Vikramjit Sahni',
      ownerPhone: '+91 98110 11223',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1002',
      title: 'Premium 3 BHK Corner Apartment in M3M Golfestate',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 36500000,
      location: 'Sector 65, Golf Course Extension Road',
      address: 'Tower Fairway East, Flat 902',
      city: 'Gurugram',
      locality: 'Sector 65',
      bedrooms: 3,
      bathrooms: 4,
      area: 3450,
      furnishing: 'Furnished',
      floor: 9,
      totalFloors: 32,
      parking: 2,
      facing: 'East',
      possessionStatus: 'Ready to Move',
      description: 'Chic golf-themed luxury living with 9-hole executive golf course in the society. Features grand living-dining space, modern wood-accented interiors, large corner deck, and designer lighting.',
      amenities: ['Golf Course', 'Infinity Pool', 'Clubhouse', 'Squash Court', 'Multi-tier Security', 'Power Backup', 'Landscaped Gardens'],
      ownerName: 'Sanjay Talwar',
      ownerPhone: '+91 98180 33445',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1003',
      title: 'Independent Luxury Designer Kothi in DLF Phase 1',
      propertyType: 'Independent House',
      transactionType: 'Sale',
      price: 92500000,
      location: 'DLF Phase 1, Near Mega Mall',
      address: 'Plot A-14, DLF Phase 1',
      city: 'Gurugram',
      locality: 'DLF Phase 1',
      bedrooms: 5,
      bathrooms: 6,
      area: 5000,
      furnishing: 'Semi-Furnished',
      floor: 1,
      totalFloors: 3,
      parking: 4,
      facing: 'North',
      possessionStatus: 'Ready to Move',
      description: 'Architect-designed independent bungalow constructed on a 500 sq yard plot. Basement lounge with private home theatre, ground floor living & dining, first floor suites, and terrace garden with gazebo.',
      amenities: ['Private Lift', 'Home Theatre', 'Terrace Garden', 'Servant Quarters', 'Solar Power', 'Italian Bath Fittings', 'CCTV Security'],
      ownerName: 'Col. R.K. Bhalla',
      ownerPhone: '+91 98100 88990',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1004',
      title: 'Spacious 3 BHK in ATS Knightsbridge Sector 124',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 48000000,
      location: 'Sector 124, Noida Expressway',
      address: 'Tower A, Floor 18',
      city: 'Noida',
      locality: 'Sector 124',
      bedrooms: 4,
      bathrooms: 5,
      area: 6000,
      furnishing: 'Unfurnished',
      floor: 18,
      totalFloors: 47,
      parking: 3,
      facing: 'North-East',
      possessionStatus: 'Ready to Move',
      description: 'Iconic twin skyscrapers right on Noida-Greater Noida Expressway near Kalindi Kunj. Single apartment per floor concept providing 360-degree skyline views.',
      amenities: ['35000 sqft Clubhouse', 'Olympic Swimming Pool', 'Helipad', 'Concierge Service', 'Private Foyer', 'Automated Smart Homes'],
      ownerName: 'Manmohan Mittal',
      ownerPhone: '+91 98711 22334',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1005',
      title: 'Designer 3 BHK Rental in Central Park Resorts',
      propertyType: 'Apartment',
      transactionType: 'Rent',
      price: 135000,
      location: 'Sector 48, Sohna Road',
      address: 'Belgravia Residences, Flat 1204',
      city: 'Gurugram',
      locality: 'Sector 48',
      bedrooms: 3,
      bathrooms: 3,
      area: 2450,
      furnishing: 'Furnished',
      floor: 12,
      totalFloors: 18,
      parking: 2,
      facing: 'North',
      possessionStatus: 'Ready to Move',
      description: 'Resort-style luxury rental featuring 20 acres of lush vehicular-free green park. Zero traffic on surface, 5-star hospitality, golf cart mobility, international restaurants inside complex.',
      amenities: ['20 Acres Green', '5-Star Hospitality Service', 'All-weather Pool', 'Multi-cuisine Club', 'Housekeeping on Call', 'Kids Creche'],
      ownerName: 'Priya Chawla',
      ownerPhone: '+91 98112 77665',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1006',
      title: 'Commercial Retail Shop in M3M Urbana',
      propertyType: 'Commercial',
      transactionType: 'Sale',
      price: 28500000,
      location: 'Sector 67, Golf Course Extension Road',
      address: 'Ground Floor, Shop G-42',
      city: 'Gurugram',
      locality: 'Sector 67',
      bedrooms: 0,
      bathrooms: 1,
      area: 850,
      furnishing: 'Furnished',
      floor: 0,
      totalFloors: 4,
      parking: 1,
      facing: 'East',
      possessionStatus: 'Ready to Move',
      description: 'High street commercial retail shop with broad double-height frontage. Excellent visibility from main boulevard road, currently leased to popular cafe brand earning steady monthly rental return.',
      amenities: ['100% Power Backup', 'Escalators & Elevators', 'Basement Parking', 'Food Court', 'High Footfall Boulevard'],
      ownerName: 'Rajinder Gupta',
      ownerPhone: '+91 98101 22339',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1007',
      title: 'Gated Residential Plot in Vatika City Central',
      propertyType: 'Plot',
      transactionType: 'Sale',
      price: 32000000,
      location: 'Sector 82, New Gurugram',
      address: 'Plot No. 118, Block B',
      city: 'Gurugram',
      locality: 'Sector 82',
      bedrooms: 0,
      bathrooms: 0,
      area: 2700, // 300 sq yards
      furnishing: 'Unfurnished',
      floor: 0,
      totalFloors: 4,
      parking: 0,
      facing: 'North-East',
      possessionStatus: 'Ready to Move',
      description: 'Clear title freehold residential plot measuring 300 sq. yards. Permissible Stilt + 4 floors construction under Haryana building bylaws with independent registry rights.',
      amenities: ['Gated Township', 'Underground Cabling', 'Wide 18-meter Road', 'Sewage Treatment', 'Security Checkpost'],
      ownerName: 'Vikas Nanda',
      ownerPhone: '+91 98114 99002',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1008',
      title: 'Modern 3 BHK in Godrej South Estate Okhla',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 49500000,
      location: 'Okhla Phase 1, South Delhi',
      address: 'Tower Emerald, 21st Floor',
      city: 'Delhi',
      locality: 'Okhla Phase 1',
      bedrooms: 3,
      bathrooms: 3,
      area: 2200,
      furnishing: 'Semi-Furnished',
      floor: 21,
      totalFloors: 29,
      parking: 2,
      facing: 'North',
      possessionStatus: 'Under Construction',
      description: 'First luxury high rise by Godrej in Delhi with air purification technology throughout common areas and homes. Dholpur stone facade architecture, grand entrance lobby, and boutique club.',
      amenities: ['Air Purifying System', 'Rooftop Lounge', 'Clubhouse', 'Heated Indoor Pool', 'State-of-art Gym'],
      ownerName: 'Naveen Jindal',
      ownerPhone: '+91 99992 44331',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1009',
      title: '4 BHK Luxury Penthouse in Pioneer Araya',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 110000000,
      location: 'Sector 62, Golf Course Ext Road',
      address: 'Penthouse Unit P-2',
      city: 'Gurugram',
      locality: 'Sector 62',
      bedrooms: 4,
      bathrooms: 5,
      area: 5500,
      furnishing: 'Furnished',
      floor: 30,
      totalFloors: 32,
      parking: 3,
      facing: 'East',
      possessionStatus: 'Ready to Move',
      description: 'Duplex penthouse with private terrace pool, sun deck, double-height living room, imported kitchen, master bedroom with walk-in wardrobe and jacuzzi.',
      amenities: ['Private Rooftop Pool', 'Double Height Living Room', 'Club Araya', 'Tennis Court', 'Squash Court', 'Multi-Cuisine Cafe'],
      ownerName: 'Sunil Duggal',
      ownerPhone: '+91 98103 44556',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Reserved',
      images: [
        'https://images.unsplash.com/photo-1502005229762-ee152da915ba?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1010',
      title: '3 BHK Builder Floor in Sector 57 Sushant Lok 2',
      propertyType: 'Independent House',
      transactionType: 'Sale',
      price: 19500000,
      location: 'Sector 57, Near Hong Kong Bazaar',
      address: 'Plot 450, 2nd Floor',
      city: 'Gurugram',
      locality: 'Sector 57',
      bedrooms: 3,
      bathrooms: 3,
      area: 1920,
      furnishing: 'Furnished',
      floor: 2,
      totalFloors: 4,
      parking: 2,
      facing: 'East',
      possessionStatus: 'Ready to Move',
      description: 'Premium newly constructed builder floor with Otis lift, stilt parking, branded Italian tiles, false ceiling, and separate servant quarter with washroom.',
      amenities: ['Reserved Stilt Parking', 'Otis Automatic Elevator', 'Gated Sector', 'Near Market & Metro'],
      ownerName: 'Ashok Sehgal',
      ownerPhone: '+91 98111 66778',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1011',
      title: 'Luxury 4 BHK Villa in Tata Primanti',
      propertyType: 'Villa',
      transactionType: 'Sale',
      price: 78000000,
      location: 'Sector 72, Southern Peripheral Road',
      address: 'Villa 18, Tata Primanti',
      city: 'Gurugram',
      locality: 'Sector 72',
      bedrooms: 4,
      bathrooms: 5,
      area: 4500,
      furnishing: 'Semi-Furnished',
      floor: 1,
      totalFloors: 3,
      parking: 2,
      facing: 'North-East',
      possessionStatus: 'Ready to Move',
      description: 'European-styled villa with basement entertainment room, private rooftop terrace, double height courtyards, and scenic landscaping.',
      amenities: ['Private Garden', 'Basement Lounge', 'Spa & Sauna', 'Squash Courts', 'Temperature Controlled Pool'],
      ownerName: 'Deepak Dewan',
      ownerPhone: '+91 98201 11229',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1012',
      title: 'Corporate Office Space in DLF Cyber City',
      propertyType: 'Office',
      transactionType: 'Rent',
      price: 450000,
      location: 'DLF Cyber City, Building 10',
      address: '7th Floor, DLF Cyber City Tower B',
      city: 'Gurugram',
      locality: 'Cyber City',
      bedrooms: 0,
      bathrooms: 4,
      area: 4500,
      furnishing: 'Furnished',
      floor: 7,
      totalFloors: 16,
      parking: 5,
      facing: 'North',
      possessionStatus: 'Ready to Move',
      description: 'Plug-and-play furnished Grade A corporate office with 60 workstations, 3 executive director cabins, 2 conference rooms, server room, and cafeteria.',
      amenities: ['Rapid Metro Connectivity', '100% Power Backup', 'Centralized HVAC', 'Fiber Optic Ready', 'Access Control Security'],
      ownerName: 'DLF Asset Management',
      ownerPhone: '+91 98110 55443',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1013',
      title: '2 BHK Smart Apartment in Signature Global Solera',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 5800000,
      location: 'Sector 107, Dwarka Expressway',
      address: 'Tower C, Flat 405',
      city: 'Gurugram',
      locality: 'Sector 107',
      bedrooms: 2,
      bathrooms: 2,
      area: 650,
      furnishing: 'Unfurnished',
      floor: 4,
      totalFloors: 14,
      parking: 1,
      facing: 'East',
      possessionStatus: 'Ready to Move',
      description: 'Affordable modern living 5 minutes from Delhi border and upcoming Diplomatic Enclave II. Well maintained society with retail market downstairs.',
      amenities: ['Kids Play Area', 'Community Hall', 'Gated Security', 'Daily Needs Market'],
      ownerName: 'Praveen Sharma',
      ownerPhone: '+91 98119 22110',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Sold',
      images: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1014',
      title: '3 BHK High-rise in Mahagun Moderne',
      propertyType: 'Apartment',
      transactionType: 'Sale',
      price: 17500000,
      location: 'Sector 78, Noida',
      address: 'Verona Tower, 11th Floor',
      city: 'Noida',
      locality: 'Sector 78',
      bedrooms: 3,
      bathrooms: 3,
      area: 1850,
      furnishing: 'Semi-Furnished',
      floor: 11,
      totalFloors: 24,
      parking: 1,
      facing: 'North',
      possessionStatus: 'Ready to Move',
      description: 'Prime residential society within walking distance to Sector 76 Metro station. Features 2 large balconies overlooking society musical fountain and central lawns.',
      amenities: ['Musical Fountain', 'Metro Walking Distance', 'Club Moderne', 'Badminton Court', 'Commercial Arcade'],
      ownerName: 'Anil Saxena',
      ownerPhone: '+91 98710 88223',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
    },
    {
      propertyCode: 'PROP-1015',
      title: 'Industrial Warehouse in Bilaspur Logistics Hub',
      propertyType: 'Warehouse',
      transactionType: 'Rent',
      price: 320000,
      location: 'NH-48 Bilaspur, Gurugram',
      address: 'Shed 4, Logistics Park',
      city: 'Gurugram',
      locality: 'Bilaspur',
      bedrooms: 0,
      bathrooms: 2,
      area: 12000,
      furnishing: 'Unfurnished',
      floor: 0,
      totalFloors: 1,
      parking: 6,
      facing: 'North',
      possessionStatus: 'Ready to Move',
      description: 'PEB industrial warehouse with 10 meter clear height, trimix laser screed flooring, 4 hydraulic dock levelers, and ample parking for heavy 14-wheeler trailers.',
      amenities: ['Hydraulic Docks', 'Fire Sprinklers FM Global Compliant', 'Ample Truck Parking', 'Guardhouse & CCTV'],
      ownerName: 'Rameshwar Logistics Ltd',
      ownerPhone: '+91 98110 33441',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Available',
      images: [
        'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
      ],
      isDemo: true,
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    },
  ];
}

export function generateDemoClients(agentId: string, agentName: string): Omit<Client, 'id'>[] {
  return [
    {
      name: 'Vikramaditya Singhania',
      phone: '+91 98112 34567',
      whatsapp: '+91 98112 34567',
      email: 'vikram.singhania@gmail.com',
      clientType: 'Buyer',
      budget: 45000000,
      preferredLocation: 'Golf Course Road, Gurugram',
      propertyType: 'Apartment',
      requirements: '4 BHK luxury apartment in DLF Magnolias or Camellias.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'High net-worth corporate chairman. Needs private viewing on weekends.',
      isDemo: true,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      name: 'Dr. Meenakshi Iyer',
      phone: '+91 98711 55443',
      email: 'meenakshi.iyer@medanta.org',
      clientType: 'Buyer',
      budget: 55000000,
      preferredLocation: 'DLF Phase 1, Gurugram',
      propertyType: 'Villa',
      requirements: 'Independent bungalow with manicured lawn.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Doctor at Medanta The Medicity.',
      isDemo: true,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      name: 'Siddharth Oberoi',
      phone: '+91 97118 77665',
      whatsapp: '+91 97118 77665',
      email: 'siddharth@oberoiventures.com',
      clientType: 'Investor',
      budget: 35000000,
      preferredLocation: 'Golf Course Extension Road',
      propertyType: 'Commercial',
      requirements: 'High street retail units with minimum 6.5% pre-leased rental yield.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Frequent commercial property investor.',
      isDemo: true,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      name: 'Kavita & Amit Bansal',
      phone: '+91 98100 44321',
      whatsapp: '+91 98100 44321',
      email: 'amit.bansal@bansalexports.com',
      clientType: 'Tenant',
      budget: 100000,
      preferredLocation: 'DLF Phase 2, Gurugram',
      propertyType: 'Apartment',
      requirements: 'Fully furnished 3 BHK apartment near CyberHub.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Moving from Bangalore on 2-year lease agreement.',
      isDemo: true,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      name: 'Harpreet Singh Gill',
      phone: '+91 98760 33221',
      email: 'hsgill@canadagroup.ca',
      clientType: 'Investor',
      budget: 70000000,
      preferredLocation: 'Southern Peripheral Road',
      propertyType: 'Plot',
      requirements: 'Gated residential plots for long term value appreciation.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'NRI client based in Vancouver.',
      isDemo: true,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      name: 'Sanjay Talwar (Owner)',
      phone: '+91 98180 33445',
      email: 'sanjay.talwar@talwartextiles.in',
      clientType: 'Seller',
      budget: 36500000,
      preferredLocation: 'Sector 65, Gurugram',
      propertyType: 'Apartment',
      requirements: 'Selling 3 BHK in M3M Golfestate.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Clean registry paper, expects quick closing.',
      isDemo: true,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    },
    {
      name: 'Col. R.K. Bhalla (Owner)',
      phone: '+91 98100 88990',
      email: 'rk.bhalla@veterans.org',
      clientType: 'Seller',
      budget: 92500000,
      preferredLocation: 'DLF Phase 1, Gurugram',
      propertyType: 'Independent House',
      requirements: 'Selling independent kothi on 500 sq yards plot.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Relocating to Pune.',
      isDemo: true,
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    },
    {
      name: 'Priya Chawla (Landlord)',
      phone: '+91 98112 77665',
      email: 'priya.chawla@luxurystays.in',
      clientType: 'Landlord',
      budget: 135000,
      preferredLocation: 'Sector 48, Sohna Road',
      propertyType: 'Apartment',
      requirements: 'Renting out Belgravia Residences flat.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Prefers MNC corporate executive tenant.',
      isDemo: true,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      name: 'Prateek & Richa Roy',
      phone: '+91 99991 88223',
      email: 'prateek.roy@google.com',
      clientType: 'Buyer',
      budget: 35000000,
      preferredLocation: 'Golf Course Extension Road',
      propertyType: 'Apartment',
      requirements: '4 BHK luxury apartment in gated society.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Works at Google Gurugram office.',
      isDemo: true,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      name: 'Kunal Khanna',
      phone: '+91 99119 88776',
      email: 'kkhanna@khannas.in',
      clientType: 'Buyer',
      budget: 75000000,
      preferredLocation: 'Tata Primanti, Sector 72',
      propertyType: 'Villa',
      requirements: 'Executive villa ready for immediate possession.',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Final stages of deal negotiation.',
      isDemo: true,
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
  ];
}

export function generateDemoFollowUps(agentId: string, agentName: string): Omit<FollowUp, 'id'>[] {
  const today = new Date().toISOString().slice(0, 10);
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
  const nextWeek = new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10);

  return [
    {
      relatedType: 'lead',
      relatedId: 'lead-1',
      relatedName: 'Vikramaditya Singhania',
      date: today,
      time: '11:30',
      type: 'Meeting',
      priority: 'High',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Final round discussion regarding DLF The Magnolias unit price and payment plan.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-2',
      relatedName: 'Ananya Deshmukh',
      date: today,
      time: '14:00',
      type: 'Call',
      priority: 'High',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Check feedback on M3M Golfestate layout plan shared on WhatsApp.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-3',
      relatedName: 'Rohan Sethi',
      date: tomorrow,
      time: '16:30',
      type: 'WhatsApp',
      priority: 'Medium',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Send location pin and gate entry pass for Sector 57 site visit.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'client',
      relatedId: 'client-1',
      relatedName: 'Dr. Meenakshi Iyer',
      date: tomorrow,
      time: '10:00',
      type: 'Call',
      priority: 'High',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Share structural drawings for DLF Phase 1 Kothi.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-4',
      relatedName: 'Kavita & Amit Bansal',
      date: yesterday,
      time: '15:00',
      type: 'Call',
      priority: 'Medium',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Rental lease draft confirmation with owner Priya Chawla.',
      status: 'Missed',
      isDemo: true,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-5',
      relatedName: 'Prateek & Richa Roy',
      date: today,
      time: '18:00',
      type: 'Meeting',
      priority: 'High',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Meeting at Pioneer Araya clubhouse with building manager.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'client',
      relatedId: 'client-2',
      relatedName: 'Siddharth Oberoi',
      date: nextWeek,
      time: '11:00',
      type: 'Meeting',
      priority: 'Medium',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Review quarterly rental yield statements for M3M Urbana unit.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-6',
      relatedName: 'Harpreet Singh Gill',
      date: yesterday,
      time: '21:00',
      type: 'Call',
      priority: 'Low',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Discuss Vatika City Central plot registry timeline across time zones.',
      status: 'Completed',
      isDemo: true,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-7',
      relatedName: 'Kunal Khanna',
      date: today,
      time: '12:00',
      type: 'WhatsApp',
      priority: 'High',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Confirm revised counter-offer of ₹ 7.6 Cr with seller Deepak Dewan.',
      status: 'Completed',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      relatedType: 'lead',
      relatedId: 'lead-8',
      relatedName: 'Pooja Narang',
      date: nextWeek,
      time: '15:30',
      type: 'Call',
      priority: 'Low',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      notes: 'Follow up on Noida Sector 150 project brochures.',
      status: 'Pending',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function generateDemoTasks(agentId: string, agentName: string): Omit<Task, 'id'>[] {
  const today = new Date().toISOString().slice(0, 10);
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);

  return [
    {
      title: 'Collect Title Deeds for DLF Phase 1 Kothi',
      description: 'Collect chain of deeds and verify encumbrance certificate from Tehsil sub-registrar office.',
      dueDate: today,
      priority: 'High',
      status: 'In Progress',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      relatedClientId: 'client-7',
      relatedClientName: 'Col. R.K. Bhalla',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Coordinate Key Handover at M3M Golfestate',
      description: 'Hand over master digital access cards and inventory checklist to buyer after registry.',
      dueDate: today,
      priority: 'High',
      status: 'Todo',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      relatedLeadId: 'lead-2',
      relatedLeadName: 'Ananya Deshmukh',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Prepare Quotation and Payment Schedule for DLF Magnolias',
      description: 'Draft milestone payment breakdown including maintenance deposit and stamp duty figures.',
      dueDate: today,
      priority: 'High',
      status: 'Completed',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      relatedLeadId: 'lead-1',
      relatedLeadName: 'Vikramaditya Singhania',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Schedule Professional Photography for Cyber City Office',
      description: 'Book architectural photographer for newly listed Building 10 corporate floor.',
      dueDate: tomorrow,
      priority: 'Medium',
      status: 'Todo',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Verify RERA Registration for Sector 150 Project',
      description: 'Download UP RERA compliance certificate and quarterly progress reports from portal.',
      dueDate: yesterday,
      priority: 'Medium',
      status: 'Completed',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      isDemo: true,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      title: 'Finalize Lease Agreement for Belgravia Residences',
      description: 'Stamp paper drafting for ₹ 1.35 Lakh monthly rent with 2 months security deposit clause.',
      dueDate: today,
      priority: 'High',
      status: 'In Progress',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      relatedClientId: 'client-8',
      relatedClientName: 'Priya Chawla',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Audit Lead Conversion Rates on MagicBricks',
      description: 'Check cost per qualified lead from June campaigns and reallocate budget.',
      dueDate: tomorrow,
      priority: 'Low',
      status: 'Todo',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Inspect Water Proofing and Balcony at Sector 57 Builder Floor',
      description: 'Conduct pre-handover snag list audit with contractor.',
      dueDate: yesterday,
      priority: 'Medium',
      status: 'Todo', // overdue
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      isDemo: true,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      title: 'Send Quarterly Property Market Report to NRI Investor Base',
      description: 'Email Gurugram & Noida luxury capital appreciation metrics to overseas buyers.',
      dueDate: tomorrow,
      priority: 'Medium',
      status: 'Todo',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      title: 'Update Sold Status and Commission Invoice for Urbana Unit G-42',
      description: 'Generate brokerage bill and send to finance team.',
      dueDate: today,
      priority: 'High',
      status: 'Completed',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function generateDemoSiteVisits(agentId: string, agentName: string): Omit<SiteVisit, 'id'>[] {
  const today = new Date().toISOString().slice(0, 10);
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  const dayAfter = new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10);
  const lastWeek = new Date(Date.now() - 6 * 86400000).toISOString().slice(0, 10);

  return [
    {
      leadName: 'Vikramaditya Singhania',
      propertyId: 'prop-1',
      propertyTitle: 'Luxury 4 BHK Sky Villa in DLF The Magnolias',
      date: today,
      time: '11:00',
      location: 'DLF Phase 5, Golf Course Road, Gurugram',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Scheduled',
      notes: 'Second visit with family architect to review interior wall customization.',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      leadName: 'Rohan Sethi',
      propertyId: 'prop-10',
      propertyTitle: '3 BHK Builder Floor in Sector 57 Sushant Lok 2',
      date: today,
      time: '15:30',
      location: 'Plot 450, Sector 57, Gurugram',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Scheduled',
      notes: 'Client arriving with car to check stilt parking bay clearance.',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      leadName: 'Prateek & Richa Roy',
      propertyId: 'prop-9',
      propertyTitle: '4 BHK Luxury Penthouse in Pioneer Araya',
      date: tomorrow,
      time: '16:00',
      location: 'Sector 62, Golf Course Ext Road, Gurugram',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Scheduled',
      notes: 'Showing penthouse terrace pool and sunset Aravali panorama.',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      leadName: 'Dr. Meenakshi Iyer',
      propertyId: 'prop-3',
      propertyTitle: 'Independent Luxury Designer Kothi in DLF Phase 1',
      date: dayAfter,
      time: '10:30',
      location: 'Plot A-14, DLF Phase 1, Gurugram',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Scheduled',
      notes: 'Checking Vaastu alignment of kitchen and master bedroom suite.',
      isDemo: true,
      createdAt: new Date().toISOString(),
    },
    {
      leadName: 'Ananya Deshmukh',
      propertyId: 'prop-2',
      propertyTitle: 'Premium 3 BHK Corner Apartment in M3M Golfestate',
      date: lastWeek,
      time: '14:00',
      location: 'Sector 65, Golf Course Extension Road',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Completed',
      notes: 'Loved the clubhouse and high floor golf view. Moved to qualification.',
      isDemo: true,
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      clientName: 'Kavita & Amit Bansal',
      propertyId: 'prop-5',
      propertyTitle: 'Designer 3 BHK Rental in Central Park Resorts',
      date: lastWeek,
      time: '17:00',
      location: 'Belgravia Residences, Sector 48, Sohna Road',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Completed',
      notes: 'Liked the furnished condition. Proceeding with lease draft.',
      isDemo: true,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      leadName: 'Tarun Bhatia',
      propertyId: 'prop-7',
      propertyTitle: 'Gated Residential Plot in Vatika City Central',
      date: lastWeek,
      time: '12:00',
      location: 'Sector 82, New Gurugram',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'Cancelled',
      notes: 'Client had urgent business travel. Rescheduling next month.',
      isDemo: true,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      leadName: 'Gaurav Aggarwal',
      propertyId: 'prop-13',
      propertyTitle: '2 BHK Smart Apartment in Signature Global Solera',
      date: lastWeek,
      time: '11:00',
      location: 'Sector 107, Dwarka Expressway',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      status: 'No Show',
      notes: 'Phone unreachable on day of visit. Lead placed on cold follow-up.',
      isDemo: true,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
  ];
}

export function generateDemoDeals(agentId: string, agentName: string): Omit<Deal, 'id'>[] {
  return [
    {
      dealName: 'Magnolias Sky Villa Acquisition',
      leadName: 'Vikramaditya Singhania',
      propertyTitle: 'Luxury 4 BHK Sky Villa in DLF The Magnolias',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 185000000,
      expectedClosingDate: new Date(Date.now() + 15 * 86400000).toISOString().slice(0, 10),
      stage: 'Negotiation',
      probability: 75,
      notes: 'Token advance expected this week. Buyer seeking 2% price adjustment on registry charges.',
      isDemo: true,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      dealName: 'Primanti Luxury Villa Deal',
      leadName: 'Kunal Khanna',
      propertyTitle: 'Luxury 4 BHK Villa in Tata Primanti',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 76000000,
      expectedClosingDate: new Date(Date.now() + 10 * 86400000).toISOString().slice(0, 10),
      stage: 'Documentation',
      probability: 90,
      notes: 'Draft sale deed with advocate. Bank loan sanctioned from HDFC Bank.',
      isDemo: true,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      dealName: 'Golfestate 3 BHK Corner Purchase',
      leadName: 'Ananya Deshmukh',
      propertyTitle: 'Premium 3 BHK Corner Apartment in M3M Golfestate',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 36500000,
      expectedClosingDate: new Date(Date.now() + 25 * 86400000).toISOString().slice(0, 10),
      stage: 'Site Visit',
      probability: 60,
      notes: 'Follow-up site visit done with parents. Very positive response.',
      isDemo: true,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      dealName: 'Pioneer Araya Duplex Penthouse',
      leadName: 'Prateek & Richa Roy',
      propertyTitle: '4 BHK Luxury Penthouse in Pioneer Araya',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 110000000,
      expectedClosingDate: new Date(Date.now() + 45 * 86400000).toISOString().slice(0, 10),
      stage: 'Qualified',
      probability: 40,
      notes: 'High intent buyers, finalizing equity liquidation for down payment.',
      isDemo: true,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      dealName: 'M3M Urbana Retail Shop G-42',
      leadName: 'Siddharth Oberoi',
      propertyTitle: 'Commercial Retail Shop in M3M Urbana',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 28500000,
      expectedClosingDate: new Date(Date.now() - 5 * 86400000).toISOString().slice(0, 10),
      stage: 'Closed Won',
      probability: 100,
      notes: 'Deal closed and full payment disbursed. Brokerage received.',
      isDemo: true,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      dealName: 'Devinder Vihar Sector 56 Lease',
      leadName: 'Deepak Varma',
      propertyTitle: 'Furnished 2 BHK Flat Sector 56',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 600000,
      expectedClosingDate: new Date(Date.now() - 10 * 86400000).toISOString().slice(0, 10),
      stage: 'Closed Won',
      probability: 100,
      notes: '11-month lease signed with ₹ 1.2 Lakh deposit.',
      isDemo: true,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      dealName: 'Faridabad Sector 82 Apartment Sale',
      leadName: 'Alok Nath Pandey',
      propertyTitle: '3 BHK High Rise Apartment',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 11500000,
      expectedClosingDate: new Date(Date.now() - 20 * 86400000).toISOString().slice(0, 10),
      stage: 'Closed Lost',
      probability: 0,
      notes: 'Client relocated to Kolkata office, transaction cancelled.',
      isDemo: true,
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    },
    {
      dealName: 'Cyber City Commercial Floor Lease',
      clientName: 'DLF Asset Management',
      propertyTitle: 'Corporate Office Space in DLF Cyber City',
      assignedAgentId: agentId,
      assignedAgentName: agentName,
      dealValue: 5400000,
      expectedClosingDate: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
      stage: 'New',
      probability: 20,
      notes: 'Pitching to prospective FinTech tenant expanding North operations.',
      isDemo: true,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
  ];
}

export function generateDemoActivities(userName: string, userId: string): Omit<Activity, 'id'>[] {
  return [
    {
      userId,
      userName,
      relatedType: 'deal',
      relatedId: 'deal-1',
      relatedName: 'Magnolias Sky Villa Acquisition',
      activityType: 'Deal Update',
      description: 'Stage advanced to Negotiation following price counter-offer.',
      timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
      isDemo: true,
    },
    {
      userId,
      userName,
      relatedType: 'lead',
      relatedId: 'lead-1',
      relatedName: 'Vikramaditya Singhania',
      activityType: 'Meeting',
      description: 'In-person meeting at DLF Club 5 to finalize floor plan choices.',
      timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
      isDemo: true,
    },
    {
      userId,
      userName,
      relatedType: 'siteVisit',
      relatedId: 'sv-1',
      relatedName: 'M3M Golfestate Visit',
      activityType: 'Site Visit',
      description: 'Site visit completed with client Ananya Deshmukh.',
      timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
      isDemo: true,
    },
    {
      userId,
      userName,
      relatedType: 'property',
      relatedId: 'prop-1',
      relatedName: 'DLF The Magnolias',
      activityType: 'Property Created',
      description: 'Added new exclusive luxury listing PROP-1001 with Aravali views.',
      timestamp: new Date(Date.now() - 36 * 3600000).toISOString(),
      isDemo: true,
    },
    {
      userId,
      userName,
      relatedType: 'lead',
      relatedId: 'lead-3',
      relatedName: 'Rohan Sethi',
      activityType: 'Call',
      description: 'Discussed builder floor bank loan eligibility and down payment requirements.',
      timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
      isDemo: true,
    },
    {
      userId,
      userName,
      relatedType: 'deal',
      relatedId: 'deal-5',
      relatedName: 'M3M Urbana Retail Shop G-42',
      activityType: 'Deal Update',
      description: 'Deal marked as Closed Won. Received confirmation of full registry token.',
      timestamp: new Date(Date.now() - 72 * 3600000).toISOString(),
      isDemo: true,
    },
  ];
}
